configName: pic32mz_w1_curiosity
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ1025W104132
projectName: ''
settings:
  PackageFilter: audio;aws_cloud;azure-rtos-threadx;bootloader;bootloader_apps_uart;bsp;bt;core;crypto;cryptoauthlib;cryptoauthlib_apps;csp;csp_apps_pic32mz_w1;csp_apps_sam_9x60;csp_apps_sam_c20_c21;csp_apps_sam_d21_da1;expresslogic_threadx;gfx;gfx_apps;micrium_ucos3;motor_control;reference_apps;net;quick_docs;touch;touch_apps;usb;wireless;x2c;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.3.177\atdf\PIC32MZ1025W104132.atdf
